clean:
	rm -rf bin/*

p1:
	mkdir -p bin && rm -f bin/p1 && gcc -o bin/p1 p1.c

p2:
	mkdir -p bin && rm -f bin/p2 && gcc -o bin/p2 p2.c

p3:
	mkdir -p bin && rm -f bin/p3 && gcc -o bin/p3 p3.c

p4:
	mkdir -p bin && rm -f bin/p4 && gcc -o bin/p4 p4.c
