make clean:
	rm -rf bin/*

make p1:
	mkdir -p bin && rm -f bin/p1 && gcc -o bin/p1 p1.c

make p2:
	mkdir -p bin && rm -f bin/p2 && gcc -o bin/p2 p2.c

make p3:
	mkdir -p bin && rm -f bin/p3 && gcc -o bin/p3 p3.c
